"""
Hybrid retrieval entry point (Phase 06.1, plan 06.1-02, RAG-05/RAG-06,
AGT-01, D-05/D-06/D-08/D-09).

Ticket: n/a (roadmap phase 06.1) | Requirements: RAG-05, RAG-06, AGT-01
Source: 06.1-02-PLAN.md Task 1 <action>; AegisX-AI-Project-Bible-v6.md
Section 15.7 (evidence provenance field set); 06.1-UI-SPEC.md's
Investigation Trace stage mapping.

This module owns the ONE seam plan 06.1-01's `app/retrieval/embeddings.py`
and `app/retrieval/qdrant_store.py` were built for A1 to call
(06.1-01-SUMMARY.md "Next Phase Readiness"). `hybrid_retrieve()` is this
plan's dense-only slice of that seam: query embedding -> Qdrant dense
search -> Postgres hydration -> a deterministic relevance-threshold gate
-> Section 15.7 evidence dicts. BM25 lexical search, Reciprocal Rank
Fusion, and batched cross-encoder reranking (`combining`/`reranking`)
are deliberately NOT implemented here -- they land in plan 06.1-03 behind
this same function signature (06.1-RESEARCH.md Pattern 2/3, Anti-Pattern
"calling the reranker once per candidate"). Both stages are emitted here
as `skipped`, never `complete`, so the Investigation Trace never claims a
capability this plan does not yet provide.

Deterministic-first boundary (D-08, CLAUDE.md): this module makes exactly
one hosted-provider call -- `call_embedding()`, for query-vector
understanding -- and zero `call_llm()`/chat-completion calls. The
relevance-threshold gate (`DENSE_RELEVANCE_THRESHOLD`) is pure Python
arithmetic over a numeric score; no model is ever asked whether a chunk is
relevant. `why_selected` sentences are composed in Python from the
retrieval method and the real score, never generated by a model (D-09's
no-fabricated-evidence rule extended to this field).

Never raises to its caller (`app.agents.minimal_specialists.run_a1`):
every failure path -- degraded embedding, unreachable Qdrant, zero
candidates, a Qdrant search error, or a Postgres hydration error -- is
caught here and returns an insufficient-evidence `RetrievalOutcome`
instead of propagating an exception. `trace` always includes an
`evaluating`/`complete` row even on these paths: the relevance check
genuinely ran (against zero or degraded candidates), so a negative result
is a real, reportable outcome, not a failure to report at all
(06.1-UI-SPEC.md Interaction Notes, stage 5's own note).
"""

import logging
from dataclasses import dataclass
from typing import Any, Dict, List, Optional

from app.retrieval.embeddings import call_embedding
from app.retrieval.qdrant_store import dense_search, get_qdrant_client

logger = logging.getLogger(__name__)

# Bible Section 15.2/15.3 sizing ("Vector Search -> 20 candidates"); plan
# 06.1-03's BM25 leg reuses the same candidate depth before fusion.
DENSE_CANDIDATE_LIMIT: int = 20

# Cosine similarity floor a dense hit must clear to be treated as relevant
# evidence (D-08's deterministic gate). Superseded as the gate's actual
# input by `RERANK_RELEVANCE_THRESHOLD` once plan 06.1-03's reranker lands
# -- this constant stays the gate for THIS plan's dense-only scoring.
DENSE_RELEVANCE_THRESHOLD: float = 0.55

# Bible Section 15.4's evidence-list cap.
MAX_EVIDENCE_ITEMS: int = 8

# 06.1-UI-SPEC.md Interaction Notes, "Investigation Trace stage mapping"
# table -- the six ordered stage ids and their exact UI labels, transcribed
# verbatim. `understanding` and `preparing` are assembled by the HTTP route
# (plan 06.1-02 Task 2) from A0's intent and the synthesis step
# respectively; this module only ever emits `searching`/`combining`/
# `reranking`/`evaluating` rows, but the full six-entry table is declared
# here as the one place both the route and every test import it from.
STAGE_LABELS: Dict[str, str] = {
    "understanding": "Understanding question",
    "searching": "Searching knowledge",
    "combining": "Combining semantic and keyword evidence",
    "reranking": "Reranking candidates",
    "evaluating": "Evaluating evidence",
    "preparing": "Preparing assessment",
}


def _stage(stage_id: str, status: str, detail: Optional[str] = None) -> Dict[str, Any]:
    """One `InvestigationStage`-shaped dict. `label` is always read from
    `STAGE_LABELS`, never restated as a literal at a call site."""
    return {"stage_id": stage_id, "label": STAGE_LABELS[stage_id], "status": status, "detail": detail}


@dataclass
class RetrievalOutcome:
    evidence: List[Dict[str, Any]]
    trace: List[Dict[str, Any]]
    insufficient_evidence: bool
    model_attribution: str


def _skipped_fusion_stages() -> List[Dict[str, Any]]:
    """`combining`/`reranking` are always `skipped` in this plan -- plan
    06.1-03 replaces these two calls with real `complete` stages behind
    this same seam."""
    return [
        _stage("combining", "skipped", "lexical fusion not yet enabled"),
        _stage("reranking", "skipped", "reranking not yet enabled"),
    ]


def _insufficient(
    stages: List[Dict[str, Any]], evaluating_detail: str, model_attribution: str
) -> RetrievalOutcome:
    stages.append(_stage("evaluating", "complete", evaluating_detail))
    return RetrievalOutcome(
        evidence=[], trace=stages, insufficient_evidence=True, model_attribution=model_attribution
    )


def _why_selected(score: float, section: Optional[str], document_title: str) -> str:
    """Composed in Python from the retrieval method and the real score --
    never generated by a model (D-09)."""
    section_label = section if section else "an unlabeled section"
    return (
        f'Semantic vector match (cosine {score:.2f}) against section '
        f'"{section_label}" of {document_title}.'
    )


def _build_evidence_item(hit: Any, row: Any) -> Dict[str, Any]:
    """One `RetrievalEvidenceItem`-shaped dict, read entirely from the
    Postgres row hydrated for `hit.chunk_id` -- the vector store is an
    index, not the source of truth (Task 1 <behavior>)."""
    document_title = row["title"] or ""
    section = row["section"]
    return {
        "evidence_id": f"EV-{str(hit.chunk_id)[:8]}",
        "document_id": row["document_id"],
        "chunk_id": str(hit.chunk_id),
        "document_title": document_title,
        "section": section,
        "page": row["page"],
        "content": row["content"],
        "retrieval_method": "semantic",
        "dense_score": round(hit.score, 4),
        "evidence_type": "document",
        "why_selected": _why_selected(hit.score, section, document_title),
    }


async def hybrid_retrieve(pool: Any, query: str, system_id: str) -> RetrievalOutcome:
    """Dense-only retrieval slice: embed the query, search Qdrant scoped to
    `system_id`, hydrate the surviving hits from Postgres, and apply the
    deterministic relevance-threshold gate. See module docstring for the
    never-raises contract and for why `combining`/`reranking` are always
    `skipped` in this plan.
    """
    stages: List[Dict[str, Any]] = []

    embedding = await call_embedding(query, task_type="RETRIEVAL_QUERY")
    if embedding.degraded:
        stages.append(_stage("searching", "skipped", embedding.failure_reason))
        stages.extend(_skipped_fusion_stages())
        return _insufficient(
            stages,
            "0 of 0 candidates cleared the relevance threshold",
            f"embedding-degraded:{embedding.failure_reason}",
        )

    client = await get_qdrant_client()
    if client is None:
        stages.append(_stage("searching", "skipped", "qdrant unavailable"))
        stages.extend(_skipped_fusion_stages())
        return _insufficient(
            stages, "0 of 0 candidates cleared the relevance threshold", "qdrant-unavailable"
        )

    try:
        hits = await dense_search(client, embedding.vector, system_id, limit=DENSE_CANDIDATE_LIMIT)
    except Exception as exc:  # noqa: BLE001 - see module docstring's never-raises contract
        logger.warning("A1 dense_search failed (system_id=%s): %s", system_id, type(exc).__name__, exc_info=True)
        stages.append(_stage("searching", "skipped", f"qdrant search failed: {type(exc).__name__}"))
        stages.extend(_skipped_fusion_stages())
        return _insufficient(
            stages, "0 of 0 candidates cleared the relevance threshold", "retrieval-error"
        )

    stages.append(_stage("searching", "complete", f"{len(hits)} candidate chunks"))
    stages.extend(_skipped_fusion_stages())

    if not hits:
        return _insufficient(
            stages, "0 of 0 candidates cleared the relevance threshold", embedding.model_id
        )

    chunk_ids = [hit.chunk_id for hit in hits]
    try:
        rows = await pool.fetch(
            "SELECT c.chunk_id, c.document_id, c.content, c.section, c.page, c.chunk_index, "
            "c.parent_chunk_id, d.title FROM document_chunks c JOIN documents d ON d.id = "
            "c.document_id WHERE c.chunk_id = ANY($1::uuid[])",
            chunk_ids,
        )
    except Exception as exc:  # noqa: BLE001 - see module docstring's never-raises contract
        logger.warning("A1 Postgres hydration failed (system_id=%s): %s", system_id, type(exc).__name__, exc_info=True)
        return _insufficient(
            stages, "0 of 0 candidates cleared the relevance threshold", "hydration-error"
        )

    row_by_chunk_id = {str(row["chunk_id"]): row for row in rows}

    # Every hit with no matching row is dropped (Task 1 <action> item e).
    # `hits` is already ranked descending by Qdrant's own scoring
    # (qdrant_store.dense_search), but this function guarantees the
    # "ordered by descending score" property itself (Task 1 <behavior>)
    # rather than merely trusting the caller's ordering.
    scored = [(hit, row_by_chunk_id[hit.chunk_id]) for hit in hits if hit.chunk_id in row_by_chunk_id]
    scored.sort(key=lambda pair: pair[0].score, reverse=True)

    total = len(scored)
    kept = [pair for pair in scored if pair[0].score >= DENSE_RELEVANCE_THRESHOLD][:MAX_EVIDENCE_ITEMS]

    stages.append(
        _stage("evaluating", "complete", f"{len(kept)} of {total} candidates cleared the relevance threshold")
    )

    if not kept:
        return RetrievalOutcome(
            evidence=[], trace=stages, insufficient_evidence=True, model_attribution=embedding.model_id
        )

    evidence = [_build_evidence_item(hit, row) for hit, row in kept]
    return RetrievalOutcome(
        evidence=evidence, trace=stages, insufficient_evidence=False, model_attribution=embedding.model_id
    )
